syntax on
syntax enable
filetype plugin indent on

"set background=light
colorscheme one
hi Normal ctermbg=none
highlight NonText ctermbg=none
highlight LineNr ctermbg=none

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'vim-airline/vim-airline'
Plug 'google/vim-maktaba'
Plug 'google/vim-codefmt'
Plug 'google/vim-glaive'
call plug#end()
call glaive#Install()

Glaive codefmt plugin[mappings]

augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  autocmd FileType c,cpp,proto,javascript,arduino,objc AutoFormatBuffer clang-format
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType html,css,sass,scss,less,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType python AutoFormatBuffer yapf
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
  autocmd FileType rust AutoFormatBuffer rustfmt
  autocmd FileType vue AutoFormatBuffer prettier
augroup END

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:airline_theme='one'
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

set encoding=utf-8
set nocompatible
set hidden
set ruler
set laststatus=2
set number
"set cursorline " Current theme looks ugly with the cursorline
set scrolloff=2
set fillchars=vert:\ "
set noerrorbells
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set nohlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set history=50
set shortmess+=I
set nolazyredraw
set mouse=a

" For Windows or Linux
set clipboard=unnamedplus

" For OSX
"set clipboard=unnamed

nnoremap <silent> <2-LeftMouse> <C-]>
"let g:python_host_prog='/usr/bin/python'
