" Shared Vim/Neovim config (Neovim loads this via ~/.config/nvim/init.lua)

" ----- General -----
set encoding=utf-8
set hidden
set number
set scrolloff=2
set signcolumn=yes
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set nohlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set noerrorbells
set mouse=a
set laststatus=2

set clipboard=unnamed

" ----- Plugins -----
call plug#begin('~/.vim/plugged')

Plug 'rakr/vim-one'
Plug 'vim-airline/vim-airline'

if has('nvim')
  Plug 'neovim/nvim-lspconfig'
  Plug 'Saghen/blink.cmp', {'tag': 'v1.*'}
  Plug 'rafamadriz/friendly-snippets'
endif

Plug 'fatih/vim-go'

call plug#end()

" vim-go: fmt on save; gopls via nvim-lspconfig
let g:go_gopls_enabled = 0
let g:go_fmt_autosave = 1
let g:go_fmt_command = 'goimports'

" ----- Appearance -----
syntax enable
set background=light
colorscheme one
let g:airline_theme = 'one'

hi Normal guibg=NONE ctermbg=NONE
hi NonText guibg=NONE ctermbg=NONE
hi LineNr guibg=NONE ctermbg=NONE

" ----- Mappings -----
nnoremap <silent> <2-LeftMouse> <C-]>
