syntax on
syntax enable
filetype plugin indent on

"set background=light
colorscheme one
hi Normal ctermbg=none
highlight NonText ctermbg=none
highlight LineNr ctermbg=none

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'vim-airline/vim-airline'
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'vim-airline/vim-airline-themes'
    "Plugin 'leafgarland/typescript-vim'
    Plugin 'w0rp/ale'
    Plugin 'Valloric/YouCompleteMe'
    Plugin 'ludovicchabant/vim-gutentags'
    Plugin 'majutsushi/tagbar'
call vundle#end()

let g:airline_theme='one'
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

set encoding=utf-8
set nocompatible
set hidden
set ruler
set laststatus=2
set number
"set cursorline " Current theme looks ugly with the cursorline
set scrolloff=2
set fillchars=vert:\ "
set noerrorbells
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set nohlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set history=50
set shortmess+=I
set nolazyredraw
set mouse=a
" For windows or OSX
"set clipboard=unnamedplus

" For Linux
set clipboard=unnamedplus

autocmd BufNewFile,BufRead * let b:ale_linters = []
let g:ale_fix_on_save = 1
let g:ale_fixers = {
\    '*': ['remove_trailing_lines', 'trim_whitespace'],
\    'c': ['clang-format'],
\    'cpp': ['clang-format'],
\    'python': ['black'],
\    'go': ['gofmt']
\}

autocmd BufNewFile,BufRead *.ts setlocal filetype=typescript

nnoremap <silent> <Leader>b :TagbarToggle<CR>
"nnoremap <silent> <2-LeftMouse> :TagbarToggle<CR>
nnoremap <silent> <2-LeftMouse> <C-]>
let g:python_host_prog='/usr/bin/python'
let g:tagbar_width = 40
let g:tagbar_autofocus = 1
let g:tagbar_compact = 1
let g:tagbar_indent = 1

let g:tagbar_type_go = {
	\ 'ctagstype' : 'go',
	\ 'kinds'     : [
		\ 'p:package',
		\ 'i:imports:1',
		\ 'c:constants',
		\ 'v:variables',
		\ 't:types',
		\ 'n:interfaces',
		\ 'w:fields',
		\ 'e:embedded',
		\ 'm:methods',
		\ 'r:constructor',
		\ 'f:functions'
	\ ],
	\ 'sro' : '.',
	\ 'kind2scope' : {
		\ 't' : 'ctype',
		\ 'n' : 'ntype'
	\ },
	\ 'scope2kind' : {
		\ 'ctype' : 't',
		\ 'ntype' : 'n'
	\ },
	\ 'ctagsbin'  : 'gotags',
	\ 'ctagsargs' : '-sort -silent'
    \ }
