" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" Plugins - Vundle Plugin Manager {{{
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  " Github Repos
  Bundle 'gmarik/vundle'
  Bundle 'Townk/vim-autoclose'
  Bundle 'scrooloose/nerdtree'
  Bundle 'kevinw/pyflakes-vim'
  " vim-scripts Repos
  Bundle 'jellybeans.vim'

" Nerdtree
  map <F3> :NERDTreeToggle<CR>
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" }}}

" General Settings {{{
  syntax on
  filetype on
  filetype plugin indent on 
  set encoding=utf-8
  set nocompatible
  set mouse=a
  set hidden
  set ruler
" }}}
  
" Appearance Settings {{{
  set background=dark
  colorscheme jellybeans
  set gfn=inconsolata
  set number                     " Line numbers
  set cursorline                 " Highlights cursor line
  set scrolloff=2                " Keep 2 scroll lines above/below cursor
  highlight OverLength ctermbg=red ctermfg=white guibg=#592929
  match OverLength /\%81v.\+/    " Highlight text exceeding 80 character limit
" }}}

" Gvim Settings {{{
  if has('gui_running')
    set guicursor+=a:blinkon0    " Cursor doesn't blink
    set guioptions-=m            " Remove menu bar
    set guioptions-=T            " Remove toolbar
    set guioptions-=r            " Remove right-hand scroll bar
  endif
" }}}
  
" Bell {{{
  set noerrorbells               " Disable annoying beeps
  set visualbell                 " Visual bell instead of beeping
" }}}
 
"" Code Folding {{{
  set foldenable                 " Enable code folding
  set foldmethod=manual          " But do it manually
  set foldlevel=99
" }}}
  
" Tab Settings {{{
  set expandtab                  " Tab -> Space
  set tabstop=4                  " Tabs count for 4 columns
  set softtabstop=4              " Tab == 4 spaces
  set shiftwidth=4               " 4 Columns with reindent options
  set backspace=indent,eol,start " Smart backspace 
  set autoindent                 " Ignore case
  set smartindent                " Except with capitals
  set pastetoggle=<F2>           " Disabling autoindent while pasting
" }}}
  
" Searching and History Settings {{{
  set nohlsearch
  set incsearch                  " Increment search
  set ignorecase                 " Case-insensitive search;
  set smartcase                  " Search becomes case sensitive if caps used
  set nobackup                   " Don't keep backups
  set noswapfile                 " Don't create a swap file
  set history=50                 " Keep 50 lines of command line history
" }}}
"
 " Other settings {{{
  set shortmess+=I               " No startup message
  set nolazyredraw               " Turn off lazy redraw
  set spelllang=en               " Set default language to English 
  set textwidth=80               " Max line width is 80
" }}}
