#!/bin/sh
#: Allow for restarting dwm without closing out of programs.
#: Add this to your /usr/local/bin
#: To actually quit dwm, run $ killall startdwm or bind that to a convenient
#: key.
while true; do
    dwm || exit
done
