#!/bin/sh
#: Allow for restarting dwm without closing out of programs.
#: To actually quit dwm, run $ killall startdwm or bind that to a convenient
#: key.
while true; do
	for pid in $(ps aux | grep dwmstatus\.sh | awk '{ print $2 }'); do
		kill $pid
	done
	bash $HOME/.config/dwm/dwmstatus.sh
    dwm || exit
done
